PREFIX ord2i: <http://example.org/ord2i#>
PREFIX time:  <http://www.w3.org/2006/time#>

SELECT ?time ?eventType ?eventId ?message ?parser
WHERE {
    ?event a ord2i:Event ;
           ord2i:hasEventType ?eventType ;
           ord2i:hasParser    ?parser .
    FILTER(?eventType IN ("UserLogon", "ProcessCreate", "SystemEvent",
                          "TaskSchedule"))
    OPTIONAL { ?event ord2i:uses ?obj .
               ?obj ord2i:hasEventID ?eventId }
    OPTIONAL { ?event ord2i:hasRawMessage ?message }
    OPTIONAL {
        ?event ord2i:hasTimeInterval ?iv .
        ?iv time:hasBeginning ?time .
    }
}
ORDER BY ?time
